import { useRef } from 'react';
import { Button } from '@/components/ui/button';
import { Printer, FlaskConical } from 'lucide-react';
import { TEST_PANELS, interpretValue, getRefRangeText, STATUS_COLORS, type LabTestPanelData } from '@/data/labTestPanels';

interface LabReportViewerProps {
    labReport: {
        lab_name?: string;
        doctor_name?: string;
        patient_age?: number;
        patient_gender?: string;
        notes?: string;
        test_panels: LabTestPanelData[];
    };
    patientName?: string;
    recordDate?: string;
}

export default function LabReportViewer({ labReport, patientName, recordDate }: LabReportViewerProps) {
    const printRef = useRef<HTMLDivElement>(null);

    const gender = (labReport.patient_gender as 'Male' | 'Female' | 'Other') || 'Male';

    const handlePrint = () => {
        if (!printRef.current) return;
        const printWindow = window.open('', '_blank');
        if (!printWindow) return;

        printWindow.document.write(`
      <html>
      <head>
        <title>Lab Report - ${patientName || 'Patient'}</title>
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; font-family: 'Segoe UI', sans-serif; }
          body { padding: 24px; color: #1a1a1a; font-size: 12px; }
          .header { text-align: center; border-bottom: 2px solid #2563eb; padding-bottom: 12px; margin-bottom: 16px; }
          .header h1 { font-size: 18px; color: #2563eb; }
          .header p { font-size: 11px; color: #666; margin-top: 2px; }
          .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 4px 16px; margin-bottom: 16px; font-size: 11px; }
          .info-grid .label { color: #666; }
          .info-grid .value { font-weight: 600; }
          .panel { margin-bottom: 16px; break-inside: avoid; }
          .panel-title { font-size: 13px; font-weight: 700; background: #f0f4ff; padding: 6px 10px; border-radius: 4px; margin-bottom: 6px; color: #1e3a5f; }
          table { width: 100%; border-collapse: collapse; font-size: 11px; }
          th { text-align: left; padding: 4px 8px; border-bottom: 1px solid #ddd; color: #666; font-weight: 600; }
          td { padding: 4px 8px; border-bottom: 1px solid #eee; }
          .normal { color: #16a34a; }
          .borderline { color: #d97706; }
          .abnormal { color: #dc2626; font-weight: 700; }
          .notes { margin-top: 12px; padding: 8px; background: #fafafa; border-radius: 4px; font-size: 11px; }
          .footer { margin-top: 24px; text-align: center; font-size: 10px; color: #999; border-top: 1px solid #eee; padding-top: 8px; }
          @media print { body { padding: 12px; } }
        </style>
      </head>
      <body>
        ${printRef.current.innerHTML}
        <div class="footer">Generated by Tempest Healthcare System &bull; ${new Date().toLocaleString()}</div>
      </body>
      </html>
    `);
        printWindow.document.close();
        printWindow.focus();
        setTimeout(() => { printWindow.print(); printWindow.close(); }, 250);
    };

    const getPanelName = (panelId: string): string => {
        if (panelId.startsWith('custom_')) return 'Custom Test Panel';
        return TEST_PANELS.find(p => p.id === panelId)?.name || panelId;
    };

    const getPanelDef = (panelId: string) => {
        if (panelId.startsWith('custom_')) return null;
        return TEST_PANELS.find(p => p.id === panelId);
    };

    return (
        <div className="space-y-4">
            {/* Print Button */}
            <div className="flex justify-end">
                <Button variant="outline" size="sm" className="gap-2" onClick={handlePrint}>
                    <Printer className="w-4 h-4" /> Print Report
                </Button>
            </div>

            {/* Printable Content */}
            <div ref={printRef}>
                {/* Header for print */}
                <div className="header" style={{ display: 'none' }}>
                    <h1>Laboratory Report</h1>
                    <p>{labReport.lab_name || 'Healthcare Lab'}</p>
                </div>

                {/* General Info */}
                <div className="bg-card rounded-xl p-4 border mb-4">
                    <div className="flex items-center gap-2 mb-3">
                        <FlaskConical className="w-4 h-4 text-primary" />
                        <h3 className="font-semibold text-foreground text-sm">Lab Report Details</h3>
                    </div>
                    <div className="info-grid grid grid-cols-2 sm:grid-cols-4 gap-3 text-sm">
                        {labReport.lab_name && (
                            <div><span className="label text-muted-foreground text-xs">Lab</span><p className="value font-medium">{labReport.lab_name}</p></div>
                        )}
                        {labReport.doctor_name && (
                            <div><span className="label text-muted-foreground text-xs">Doctor</span><p className="value font-medium">{labReport.doctor_name}</p></div>
                        )}
                        {patientName && (
                            <div><span className="label text-muted-foreground text-xs">Patient</span><p className="value font-medium">{patientName}</p></div>
                        )}
                        {recordDate && (
                            <div><span className="label text-muted-foreground text-xs">Date</span><p className="value font-medium">{new Date(recordDate).toLocaleDateString()}</p></div>
                        )}
                        {labReport.patient_age && (
                            <div><span className="label text-muted-foreground text-xs">Age</span><p className="value font-medium">{labReport.patient_age} yrs</p></div>
                        )}
                        {labReport.patient_gender && (
                            <div><span className="label text-muted-foreground text-xs">Gender</span><p className="value font-medium">{labReport.patient_gender}</p></div>
                        )}
                    </div>
                </div>

                {/* Test Panels */}
                {labReport.test_panels.map((panelData, idx) => {
                    const def = getPanelDef(panelData.panelId);
                    const panelName = getPanelName(panelData.panelId);

                    return (
                        <div key={idx} className="panel bg-card rounded-xl border mb-3 overflow-hidden">
                            <div className="panel-title bg-primary/5 px-4 py-2.5 border-b">
                                <h4 className="font-semibold text-foreground text-sm">{panelName}</h4>
                            </div>
                            <div className="overflow-x-auto">
                                <table className="w-full text-sm">
                                    <thead>
                                        <tr className="border-b">
                                            <th className="text-left px-4 py-2 text-xs text-muted-foreground font-medium">Test</th>
                                            <th className="text-left px-4 py-2 text-xs text-muted-foreground font-medium">Result</th>
                                            <th className="text-left px-4 py-2 text-xs text-muted-foreground font-medium">Unit</th>
                                            <th className="text-left px-4 py-2 text-xs text-muted-foreground font-medium">Reference</th>
                                            <th className="text-center px-4 py-2 text-xs text-muted-foreground font-medium">Status</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {Object.entries(panelData.values).map(([key, val]) => {
                                            if (!val.value) return null;
                                            const field = def?.fields.find(f => f.key === key);
                                            const status = field ? interpretValue(val.value, field, gender) : val.status;
                                            const colors = status ? STATUS_COLORS[status] : null;

                                            return (
                                                <tr key={key} className={`border-b last:border-0 ${colors ? colors.bg : ''}`}>
                                                    <td className="px-4 py-2 text-foreground">{field?.label || key}</td>
                                                    <td className={`px-4 py-2 font-semibold ${colors ? colors.text : 'text-foreground'}`}>{val.value}</td>
                                                    <td className="px-4 py-2 text-muted-foreground text-xs">{field?.unit || ''}</td>
                                                    <td className="px-4 py-2 text-muted-foreground text-xs">{field ? getRefRangeText(field, gender) : '—'}</td>
                                                    <td className="px-4 py-2 text-center">
                                                        {status && <div className={`inline-block w-2.5 h-2.5 rounded-full ${colors!.dot}`} title={status} />}
                                                    </td>
                                                </tr>
                                            );
                                        })}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    );
                })}

                {/* Notes */}
                {labReport.notes && (
                    <div className="notes bg-muted/30 rounded-xl p-4 border">
                        <p className="text-xs font-medium text-muted-foreground mb-1">Notes / Observations</p>
                        <p className="text-sm text-foreground">{labReport.notes}</p>
                    </div>
                )}
            </div>
        </div>
    );
}
